services:
  database:
    image: mongo:7.0
    container_name: Worthinator-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=P@ssw0rd
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - Worthinator-net
    healthcheck:
      test: ["CMD", "mongosh", "--authenticationDatabase", "admin", "-u", "admin", "-p", "P@ssw0rd", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
      
  api-inator:
    build:
      context: .
      dockerfile: src/ApiInator/Dockerfile
    container_name: api-inator
    ports:
      - "13001:13001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=mongodb://admin:P%40ssw0rd@database:27017/WorthinatorDb?authSource=admin
      - Kestrel__Endpoints__Http__Url=http://*:13001
      - Kestrel__Endpoints__Http__Protocols=Http2
    depends_on:
      database:
        condition: service_healthy
    networks:
      - Worthinator-net

  gateway:
    build:
      context: .
      dockerfile: src/Gateway.Frontend/Dockerfile
    container_name: gateway-frontend
    ports:
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__Https__Url=https://*:443
      - Kestrel__Certificates__Default__Password=P@ssw0rd
      - Kestrel__Certificates__Default__Path=/certs/gateway.pfx
      - ReverseProxy__Routes__api-route__Transforms__0__PathRemovePrefix=/api
      - ReverseProxy__Clusters__api-cluster__Destinations__destination1__Address=http://api-inator:13001
      - ReverseProxy__Clusters__portal-cluster__Destinations__destination1__Address=http://portal:80
      - ReverseProxy__Clusters__api-cluster__HttpRequest__Version=2
      - ReverseProxy__Clusters__api-cluster__HttpRequest__VersionPolicy=RequestVersionExact
    volumes:
      - ./certs:/certs:ro,Z
    depends_on:
      - api-inator
    networks:
      - Worthinator-net

  portal:
    build:
      context: ./src/Portal
      dockerfile: Dockerfile
    container_name: portal
    ports:
      - "4200:80"
    depends_on:
      - api-inator
    networks:
      - Worthinator-net

networks:
  Worthinator-net:
    driver: bridge

volumes:
  mongo-data: