// <auto-generated />
using System;
using ApiInator.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiInator.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiInator.Model.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("ApiInator.Model.GameInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("WorthFactor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("GameInfo");
                });

            modelBuilder.Entity("ApiInator.Model.GgDealsInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GgDealsInfo");
                });

            modelBuilder.Entity("ApiInator.Model.HowLongToBeatInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Completionist")
                        .HasColumnType("float");

                    b.Property<string>("HowLongToBeatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainExtra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MainStory")
                        .HasColumnType("float");

                    b.Property<int>("Releases")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("HowLongToBeatInfo");
                });

            modelBuilder.Entity("ApiInator.Model.OpenCriticInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasLootboxes")
                        .HasColumnType("bit");

                    b.Property<double>("MedianScore")
                        .HasColumnType("float");

                    b.Property<string>("OpenCriticId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PercentRecomended")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("OpenCriticInfo");
                });

            modelBuilder.Entity("ApiInator.Model.SteamInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SteamAppId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinyImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SteamInfo");
                });

            modelBuilder.Entity("ApiInator.Model.GgDealsInfo", b =>
                {
                    b.HasOne("ApiInator.Model.GameInfo", null)
                        .WithOne("GgDeals")
                        .HasForeignKey("ApiInator.Model.GgDealsInfo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ApiInator.Model.Price", "CurrentKeyshopPrice", b1 =>
                        {
                            b1.Property<Guid>("GgDealsInfoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CurrentKeyshopPrice_CurrencyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("CurrentKeyshopPrice_Value");

                            b1.HasKey("GgDealsInfoId");

                            b1.HasIndex("CurrentKeyshopPrice_CurrencyId");

                            b1.ToTable("GgDealsInfo");

                            b1.HasOne("ApiInator.Model.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("CurrentKeyshopPrice_CurrencyId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("GgDealsInfoId");

                            b1.Navigation("Currency");
                        });

                    b.OwnsOne("ApiInator.Model.Price", "CurrentRetailPrice", b1 =>
                        {
                            b1.Property<Guid>("GgDealsInfoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CurrentRetailPrice_CurrencyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("CurrentRetailPrice_Value");

                            b1.HasKey("GgDealsInfoId");

                            b1.HasIndex("CurrentRetailPrice_CurrencyId");

                            b1.ToTable("GgDealsInfo");

                            b1.HasOne("ApiInator.Model.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("CurrentRetailPrice_CurrencyId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("GgDealsInfoId");

                            b1.Navigation("Currency");
                        });

                    b.OwnsOne("ApiInator.Model.Price", "HistoricalKeyshopPrice", b1 =>
                        {
                            b1.Property<Guid>("GgDealsInfoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("HistoricalKeyshopPrice_CurrencyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("HistoricalKeyshopPrice_Value");

                            b1.HasKey("GgDealsInfoId");

                            b1.HasIndex("HistoricalKeyshopPrice_CurrencyId");

                            b1.ToTable("GgDealsInfo");

                            b1.WithOwner()
                                .HasForeignKey("GgDealsInfoId");

                            b1.HasOne("ApiInator.Model.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("HistoricalKeyshopPrice_CurrencyId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("Currency");
                        });

                    b.OwnsOne("ApiInator.Model.Price", "HistoricalRetailPrice", b1 =>
                        {
                            b1.Property<Guid>("GgDealsInfoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("HistoricalRetailPrice_CurrencyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("HistoricalRetailPrice_Value");

                            b1.HasKey("GgDealsInfoId");

                            b1.HasIndex("HistoricalRetailPrice_CurrencyId");

                            b1.ToTable("GgDealsInfo");

                            b1.WithOwner()
                                .HasForeignKey("GgDealsInfoId");

                            b1.HasOne("ApiInator.Model.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("HistoricalRetailPrice_CurrencyId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("Currency");
                        });

                    b.Navigation("CurrentKeyshopPrice")
                        .IsRequired();

                    b.Navigation("CurrentRetailPrice")
                        .IsRequired();

                    b.Navigation("HistoricalKeyshopPrice")
                        .IsRequired();

                    b.Navigation("HistoricalRetailPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("ApiInator.Model.HowLongToBeatInfo", b =>
                {
                    b.HasOne("ApiInator.Model.GameInfo", null)
                        .WithOne("HowLongToBeat")
                        .HasForeignKey("ApiInator.Model.HowLongToBeatInfo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiInator.Model.OpenCriticInfo", b =>
                {
                    b.HasOne("ApiInator.Model.GameInfo", null)
                        .WithOne("OpenCritic")
                        .HasForeignKey("ApiInator.Model.OpenCriticInfo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiInator.Model.SteamInfo", b =>
                {
                    b.HasOne("ApiInator.Model.GameInfo", null)
                        .WithOne("SteamInfo")
                        .HasForeignKey("ApiInator.Model.SteamInfo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ApiInator.Model.Price", "InitialPrice", b1 =>
                        {
                            b1.Property<Guid>("SteamInfoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("InitialPrice_CurrencyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Value")
                                .HasColumnType("float")
                                .HasColumnName("InitialPrice_Value");

                            b1.HasKey("SteamInfoId");

                            b1.HasIndex("InitialPrice_CurrencyId");

                            b1.ToTable("SteamInfo");

                            b1.HasOne("ApiInator.Model.Currency", "Currency")
                                .WithMany()
                                .HasForeignKey("InitialPrice_CurrencyId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("SteamInfoId");

                            b1.Navigation("Currency");
                        });

                    b.Navigation("InitialPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("ApiInator.Model.GameInfo", b =>
                {
                    b.Navigation("GgDeals")
                        .IsRequired();

                    b.Navigation("HowLongToBeat")
                        .IsRequired();

                    b.Navigation("OpenCritic")
                        .IsRequired();

                    b.Navigation("SteamInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
